### ISSUE TITLE
Webpaste was working good but , now don't Output th result in the Terminal 

### ISSUE THREAD

**Issue by Deku-izuku-dotcom** [tomnomnom/hacks#26]
Hello 

I just face the probleme mentioned in the title 

I didn't change anything no update.

in past it's work correctly , but now he didn't work any more 

can you check it please 
@tomnomnom

**Comment by havocker** [comment]
I installed it fresh yesterday, I tested on Brave, Chromium and Chrome, and I'm having the same issue: nothing appears on the terminal. The extension installs ok, it even goes to the next page when I click "Google URLs", but still... nothing on the console. Maybe the snippet code needs some additional tweaking? (I don't know much about javascript, yet)

**Comment by calcabuggywebsiteacom** [comment]
Edit the code for google urls like this: 
```
[...document.querySelectorAll('div.yuRUbf>a:first-child')].map(n=>n.href)
```
It will work again.

**Comment by Deku-izuku-dotcom** [comment]
It's Work , Thank you

**Comment by LucasOneZ** [comment]
> `[...document.querySelectorAll('div.yuRUbf>a:first-child')].map(n=>n.href)`


this isnt working for me i guess

**Comment by LucasOneZ** [comment]
[...document.querySelectorAll('div.yuRUbf a')].map(n=>n.href)

i got it , i was having same issue but this time i created my own js to pull href , and it worked
