### ISSUE TITLE
webpaste is not working with me

### ISSUE THREAD

**Issue by theleecher** [tomnomnom/hacks#28]
Hello tomnomnom, i have used webpaste before and it was working fine now it's not working with me i tried it on different platforms and it didn't worked on all of them, i want to know if the problem only occurs with me and how can i trace to solve it

![1](https://user-images.githubusercontent.com/16206326/97173803-d1aad100-1799-11eb-922b-fa3c17bdb71f.png)
![2](https://user-images.githubusercontent.com/16206326/97173807-d2dbfe00-1799-11eb-915c-88c40533667a.png)
![3](https://user-images.githubusercontent.com/16206326/97173808-d2dbfe00-1799-11eb-8c78-54f8a877abad.png)

**Comment by jlcg-qcert** [comment]
Looks like the snippet for Google URLs isn't working anymore, I guess they changed something on how the HTML is displayed. This selector:

[...document.querySelectorAll('div.r>a:first-child')].map(n=>n.href)

Doesn't seem to match anything. I'm trying to get a snippet working but haven't come up with any solution yet, removing the ".r" in the snippet throws unwanted URLs in the output.
