### ISSUE TITLE
Webpaste not showing any result 

### ISSUE THREAD

**Issue by remonsec** [tomnomnom/hacks#45]
Hello
I have done all configuration well, but still webpaste not showing any result back
Can you please look into it !!! Thanks 

https://user-images.githubusercontent.com/54717234/148184773-7045d3a5-daf1-44c5-8ae6-7122ddcb02e6.mp4

**Comment by darkc0d37** [comment]
Google has changed their codebase recently. Use this below snippet to get the result
```
[...document.querySelectorAll('div.yuRUbf>a:first-child')].map(n=>n.href)
```

**Comment by remonsec** [comment]
Thanks a lot
I can confirm that it's working now

![webpaste](https://user-images.githubusercontent.com/54717234/148188512-0519d39d-f686-4ce8-9106-e6ab237edad5.png)
