### ISSUE TITLE
having trouble installing hacks/anti-burl

### ISSUE THREAD

**Issue by AoxLir** [tomnomnom/hacks#69]
![image](https://github.com/tomnomnom/hacks/assets/98155826/2cb6a86f-e277-4760-866e-22485e31b690)
![image](https://github.com/tomnomnom/hacks/assets/98155826/21383afa-c6ec-4830-a4a2-d5d1c9e469a0)
![image](https://github.com/tomnomnom/hacks/assets/98155826/37440630-c967-4175-8197-36d71933e60a)
![image](https://github.com/tomnomnom/hacks/assets/98155826/cdcb870a-788e-42c5-b82a-6a910cde1074)
no matter what I did, I couldn't install it

![image](https://github.com/tomnomnom/hacks/assets/98155826/deae6f08-b5bb-4414-9dde-88391acd6bc8)

**Comment by PushkraJ99** [comment]
use command 

go install github.com/tomnomnom/hacks/anti-burl@latest
